springdoc:
  title: "Calculator project"
  description: "This project have a goal to provide math operations"
  version: 'v1'
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true

  show-actuator: true






